on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📦 Copy package.json to dist
      run: |
        cp package.json dist/
        cd dist
        npm install
        npm run build
        cd ..
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
